name: Terraform Plan (Manual)

on:
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::393800486110:role/ThoughtSpark_Terraform_Role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Plan
        env:
          TF_VAR_query_lambda_source_hash: "dGhpcy1pcy1hLWZha2UtaGFzaA=="
          TF_VAR_log_lambda_source_hash: "dGhpcy1pcy1hLWZha2UtaGFzaA=="
        run: terraform plan -out=tfplan
        working-directory: ./infra

      - name: Show Plan Output
        run: terraform show -no-color tfplan
        working-directory: ./infra
