name: Terraform Apply (Manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type YES to confirm apply'
        required: true

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'YES' }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::393800486110:role/ThoughtSpark_Terraform_Role
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build Lambda ZIP package
        run: |
          cd lambda
          pip install -r requirements.txt -t .
          zip -r ../lambda.zip .

      - name: Upload ZIP to S3
        run: aws s3 cp lambda.zip s3://thoughtspark-lambda-code/thoughtspark/lambda.zip

      - name: Calculate Lambda ZIP hash
        id: ziphash
        run: |
          HASH=$(openssl dgst -sha256 -binary lambda.zip | base64)
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Apply
        env:
          TF_VAR_lambda_s3_bucket: thoughtspark-lambda-code
          TF_VAR_lambda_s3_key: thoughtspark/lambda.zip
          TF_VAR_lambda_source_hash: ${{ steps.ziphash.outputs.hash }}
        run: terraform apply -auto-approve
        working-directory: ./infra
